GET http://localhost:3000/users/apple4333215@gmail.com
###

POST http://localhost:3000/users/test123@gmail.com
Content-Type: application/json

{
    "movid": "52525",
    "title": "Cars 3",
    "poster": "/jlashdkf"
}


###
POST http://localhost:3000/users/apple4333215@gmail.com
Content-Type: application/json

{
    "movid": "443233",
    "title": "Jokers",
    "poster": "/jlashdkf"
}
 